### ISSUE TITLE
Cannot invoke "com.earth2me.essentials.User.getHomes()" because "user" is null

### ISSUE THREAD

**Issue by candy999** [pop4959/BlueMap-Essentials#10]
### Expected result

[10:17:06 INFO]: [BlueMap] Baking resources...
[10:17:06 INFO]: [BlueMap] Resources loaded.
[10:17:06 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[10:17:06 INFO]: [BlueMap] WebServer bound to: 0.0.0.0/0.0.0.0:8123
[10:17:06 INFO]: [BlueMap] WebServer started.
[10:17:10 INFO]: [BlueMap] Loaded!
### Actual result

[10:17:06 INFO]: [BlueMap] Baking resources...
[10:17:06 INFO]: [BlueMap] Resources loaded.
[10:17:06 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[10:17:06 INFO]: [BlueMap] WebServer bound to: 0.0.0.0/0.0.0.0:8123
[10:17:06 INFO]: [BlueMap] WebServer started.
[10:17:10 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.User.getHomes()" because "user" is null
        at org.popcraft.bluemapessentials.BlueMapEssentials.addHomeMarkers(BlueMapEssentials.java:140) ~[BlueMap-Essentials.jar:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.addMarkers(BlueMapEssentials.java:91) ~[BlueMap-Essentials.jar:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.lambda$onEnable$0(BlueMapEssentials.java:50) ~[BlueMap-Essentials.jar:?]
        at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:201) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:137) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:319) ~[BlueMap.jar:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[BlueMap.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:17:10 INFO]: [BlueMap] Loaded!
### Context
**BlueMap Version:**  
`BlueMap 3.7`
`Current: git-Purpur-1861 (MC: 1.19.3)*`
`EssentialsX  2.20.0-dev+20-582a357 (build 1441, commit 582a357)`

**Comment by pop4959** [comment]
I haven't seen this issue until now but can you try using the latest version of Essentials and Paper to see if it still happens?

In general I don't see how this error could happen because the plugin pulls the users from Essentials so they should already exist, unless there is some corrupt data or something weird going on.

**Comment by candy999** [comment]
EssentialsX-2.19.7
![image](https://user-images.githubusercontent.com/2743971/211145003-65f8cd31-e65f-40a7-a619-c265b4725ad4.png)

EssentialsX-2.20.0-dev+38-b323860
![image](https://user-images.githubusercontent.com/2743971/211145028-089deb72-8fc4-469d-82df-4f0bc7f797c3.png)

https://essentialsx.net/downloads.html
![image](https://user-images.githubusercontent.com/2743971/211145051-a511a710-cbe2-4215-88d2-883017534f96.png)

**Comment by pop4959** [comment]
Thanks for your quick response and your patience. I will see if I can replicate the issue this weekend.

**Comment by pop4959** [comment]
I'm not able to produce this error on any combination of the following:

Paper 1.19.3-371 OR Purpur 1.19.3-1886
BlueMap 3.9
EssentialsX 2.19.7 OR 2.20.0-dev+38
BlueMap Essentials 1.1.0

I would try updating again and see if that helps. If not, please add me on Discord and send your Essentials userdata because I suspect updating it from 2.19.7 to 2.20.0-dev may have caused some issues.

**Comment by candy999** [comment]
My plugins
https://drive.google.com/file/d/1wIQz4M6DmqldpYiCgNtkgZRyn32lKcfS/view?usp=sharing
sorry I go to Japan travel, just returned home

**Comment by pop4959** [comment]
No worries. Can you try the [latest build](https://github.com/pop4959/BlueMap-Essentials/actions/runs/3920491063) and see if that fixes it for you?

**Comment by candy999** [comment]
![image](https://user-images.githubusercontent.com/2743971/212502465-fe49a81f-53d5-4e52-9459-45628e856c7b.png)
fixed!
Thank you💕

**Comment by pop4959** [comment]
Thanks for confirming :)

I'll release this now on Spigot as well in case others are having issues with this
