### ISSUE TITLE
NPE on getWorld()

### ISSUE THREAD

**Issue by SlimeDog** [pop4959/BlueMap-Essentials#6]
Spigot 1.18.1-3388
EssentialsX 2.19.3-dev+6-739600e
BlueMap 1.7.2
BlueBridgeCore 1.3.1
BlueMap-Essentials 1.0.3

No errors on server start-up. When moving to home in world_city
```
[20:53:15] [Craft Scheduler Thread - 89/WARN]: [BlueMap-Essentials] Plugin BlueMap-Essentials v1.0.3 generated an exception while executing task 8671
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "homeLocation" is null
        at org.popcraft.bluemapessentials.BlueMapEssentials.addHomeMarkers(BlueMapEssentials.java:161) ~[?:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.addMarkers(BlueMapEssentials.java:106) ~[?:?]
        at org.popcraft.bluemapessentials.BlueMapEssentials.refreshMarkers(BlueMapEssentials.java:207) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3388-Spigot-9fd34ab-fb92f34]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3388-Spigot-9fd34ab-fb92f34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by pop4959** [comment]
Just set up [actions](https://github.com/pop4959/BlueMap-Essentials/actions) so you can download and check, let me know if it's still an issue or not. I believe it should be fixed in the latest build, but I wasn't getting the error myself.

**Comment by SlimeDog** [comment]
NPE is gone, but I see no Essentials homes markers. Will pursue in discussion. Thanks.

**Comment by pop4959** [comment]
I fixed the NPE by just adding a null check, but it handles it by skipping the presumably invalid home. Really, it doesn't make sense since each of the homes defined in `user.getHomes()` should at least return a home location. The only validation that was needed before was to see if the world exists (since it's possible a home could be loaded for which the world wasn't).

It could be a bug in Essentials, but I think more likely your homes file is somehow broken. Feel free to investigate yourself and follow up if you figure anything out.

**Comment by SlimeDog** [comment]
Thanks for the info. This server has only one test player (myself) and the EssentialsX userdata file looks fine. It contains a lot of homes, most likely including some in dangerous locations, due to the generation of replacement MC 1.18 chunks in many of the worlds. It also includes a few homes defined in a world that no longer exists, which probably caused the NPE. Skipping over them sounds like the correct action. Thanks.

The "no homes markers" above was my error, due to configuration: `homes.online-players-only: true`. Now that it is false, the homes are displayed with the player off-line.

**Comment by pop4959** [comment]
I don't think it cares about dangerous locations (only Essentials does, and only when you actually try to teleport there), but it makes sense that it was an issue with being offline. BlueMap-Essentials doesn't render markers for offline players by default since on larger servers this could cripple the map with the number of icons. For small servers it is fine to turn off.
